#!/usr/bin/env bash
# Sync upstream awslabs/aidlc-workflows into our references/ directories.
# Usage: ./scripts/sync-upstream.sh [--ref <git-ref>] [--url <git-url>]
set -euo pipefail

UPSTREAM_URL="${UPSTREAM_URL:-https://github.com/awslabs/aidlc-workflows.git}"
REF="main"
REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref)
      REF="$2"
      shift 2
      ;;
    --url)
      UPSTREAM_URL="$2"
      shift 2
      ;;
    *)
      echo "unknown arg: $1" >&2
      exit 2
      ;;
  esac
done

# Helper: create a stub SKILL.md for a newly auto-mirrored directory.
# Does nothing if the file already exists (preserves hand-authored content).
create_stub_skill_md() {
  local skill_name="$1"
  local category="$2"
  local variant="$3"
  local skill_md="$REPO_ROOT/skills/$skill_name/SKILL.md"
  if [[ -f "$skill_md" ]]; then
    return 0
  fi
  mkdir -p "$REPO_ROOT/skills/$skill_name"
  local label_category
  local label_variant
  label_category="$(echo "$category" | sed 's/[-_]/ /g')"
  label_variant="$(echo "$variant" | sed 's/[-_]/ /g')"
  local title="AI-DLC — ${label_category}${variant:+ (${label_variant})}"
  cat > "$skill_md" <<EOF
---
name: $skill_name
description: AI-DLC ${label_category}${variant:+ ($label_variant)} extension. Use when working on ${label_category}${variant:+ ($label_variant)} concerns within an AI-DLC workflow.
---
# $title

<!-- AUTO-STUB: refine this description and orientation before release -->

This is an auto-stubbed skill mirrored from upstream when a new directory was
detected. See \`references/\` for upstream guidance.

<!-- AUTO-REFS:START -->
<!-- regenerated by scripts/lib/auto_refs.py -->
<!-- AUTO-REFS:END -->
EOF
}

# Helper: create a stub slash command for a newly auto-mirrored skill.
create_stub_command() {
  local skill_name="$1"
  local cmd_md="$REPO_ROOT/commands/$skill_name.md"
  if [[ -f "$cmd_md" ]]; then
    return 0
  fi
  cat > "$cmd_md" <<EOF
---
name: $skill_name
description: Jump directly to the $skill_name AI-DLC skill.
---
Activate the \`$skill_name\` skill and apply its guidance to the current task.
EOF
}

# 1. Clone upstream
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
echo "Cloning $UPSTREAM_URL @ $REF..."
if ! git clone --depth 1 --branch "$REF" "$UPSTREAM_URL" "$TMP/upstream" >/dev/null 2>&1; then
  # --branch only accepts tags/branches, not arbitrary SHAs.
  # Fall back to full clone + checkout.
  rm -rf "$TMP/upstream"
  git clone "$UPSTREAM_URL" "$TMP/upstream" >/dev/null 2>&1
  git -C "$TMP/upstream" checkout "$REF"
fi
UPSTREAM_RULES="$TMP/upstream/aidlc-rules"

# 2. Tree-shape verification
echo "Verifying upstream tree shape..."
required_paths=(
  "$UPSTREAM_RULES/aws-aidlc-rules/core-workflow.md"
  "$UPSTREAM_RULES/aws-aidlc-rule-details/common"
  "$UPSTREAM_RULES/aws-aidlc-rule-details/inception"
  "$UPSTREAM_RULES/aws-aidlc-rule-details/construction"
  "$UPSTREAM_RULES/aws-aidlc-rule-details/operations"
  "$UPSTREAM_RULES/aws-aidlc-rule-details/extensions"
)
for p in "${required_paths[@]}"; do
  if [[ ! -e "$p" ]]; then
    echo "FAIL: required upstream path missing: $p" >&2
    echo "Upstream may have restructured. Update scripts/sync-upstream.sh mapping." >&2
    exit 1
  fi
done
echo "Tree shape OK."

# 3. Mirror core-workflow.md and the four known phases
KNOWN_PHASES=(common inception construction operations)
mkdir -p "$REPO_ROOT/skills/aidlc/references"
cp "$UPSTREAM_RULES/aws-aidlc-rules/core-workflow.md" \
   "$REPO_ROOT/skills/aidlc/references/core-workflow.md"
for phase in "${KNOWN_PHASES[@]}"; do
  src="$UPSTREAM_RULES/aws-aidlc-rule-details/$phase"
  dst="$REPO_ROOT/skills/aidlc-$phase/references"
  mkdir -p "$dst"
  rsync -a --delete --include='*.md' --exclude='*' "$src/" "$dst/"
done

# 4. Mirror known extensions; auto-stub unknown ones
EXT_ROOT="$UPSTREAM_RULES/aws-aidlc-rule-details/extensions"
# Format: "relative/path:skill-name" — add entries here when upstream adds extensions
KNOWN_EXT=(
  "security/baseline:aidlc-ext-security-baseline"
  "testing/property-based:aidlc-ext-testing-property"
)

# Helper: look up a skill name for a known extension rel-path.
# Prints skill name and returns 0 if found; prints nothing and returns 1 if unknown.
lookup_known_ext() {
  local needle="$1"
  for entry in "${KNOWN_EXT[@]}"; do
    local k="${entry%%:*}"
    local v="${entry##*:}"
    if [[ "$k" == "$needle" ]]; then
      echo "$v"
      return 0
    fi
  done
  return 1
}

# Mirror all known extensions first
for entry in "${KNOWN_EXT[@]}"; do
  key="${entry%%:*}"
  skill="${entry##*:}"
  src="$EXT_ROOT/$key"
  if [[ -d "$src" ]]; then
    dst="$REPO_ROOT/skills/$skill/references"
    mkdir -p "$dst"
    rsync -a --delete --include='*.md' --exclude='*' "$src/" "$dst/"
  fi
done
echo "Checking for new extension subdirectories..."
while IFS= read -r -d '' variant_dir; do
  rel="${variant_dir#"$EXT_ROOT"/}"
  if ! lookup_known_ext "$rel" > /dev/null 2>&1; then
    category="${rel%%/*}"
    variant="${rel##*/}"
    new_skill="aidlc-ext-${category}-${variant}"
    echo "STUB CREATED: $new_skill (refine description before release)"
    dst="$REPO_ROOT/skills/$new_skill/references"
    mkdir -p "$dst"
    rsync -a --delete --include='*.md' --exclude='*' "$variant_dir/" "$dst/"
    create_stub_skill_md "$new_skill" "$category" "$variant"
    create_stub_command "$new_skill"
  fi
done < <(find "$EXT_ROOT" -mindepth 2 -maxdepth 2 -type d -print0)

# 5. Auto-stub for any new top-level phase directory
echo "Checking for new top-level phases..."
PHASE_ROOT="$UPSTREAM_RULES/aws-aidlc-rule-details"
while IFS= read -r -d '' phase_dir; do
  phase_name="$(basename "$phase_dir")"
  case "$phase_name" in
    common|inception|construction|operations|extensions) continue ;;
  esac
  new_skill="aidlc-${phase_name}"
  echo "STUB CREATED: $new_skill (new phase! also update skills/aidlc/SKILL.md routing)"
  dst="$REPO_ROOT/skills/$new_skill/references"
  mkdir -p "$dst"
  rsync -a --delete --include='*.md' --exclude='*' "$phase_dir/" "$dst/"
  create_stub_skill_md "$new_skill" "$phase_name" ""
  create_stub_command "$new_skill"
done < <(find "$PHASE_ROOT" -mindepth 1 -maxdepth 1 -type d -print0)

# 6. Regenerate AUTO-REFS in all SKILL.md files
echo "Regenerating AUTO-REFS sections..."
python3 "$REPO_ROOT/scripts/lib/auto_refs.py" "$REPO_ROOT/skills"

# 7. Capture upstream SHA and update NOTICE
UPSTREAM_SHA="$(git -C "$TMP/upstream" rev-parse HEAD)"
echo "$UPSTREAM_SHA" > "$REPO_ROOT/.upstream-version"
if ! grep -q "Upstream commit at last sync:" "$REPO_ROOT/NOTICE"; then
  echo "WARNING: NOTICE missing 'Upstream commit at last sync:' line; not updated." >&2
else
  sed -i.bak "s|Upstream commit at last sync: .*|Upstream commit at last sync: $UPSTREAM_SHA|" \
    "$REPO_ROOT/NOTICE"
  rm -f "$REPO_ROOT/NOTICE.bak"
fi

echo ""
echo "Sync complete. Upstream SHA: $UPSTREAM_SHA"
echo "Run 'git status' to review changes."
